const PRODUCT_LOADING = "PRODUCT_LOADING";
const PRODUCT_ERROR = "PRODUCT_ERROR";
const PRODUCT_SUCCES = "PRODUCT_SUCCES";

const CURRENT_PRODUCT_LOADING = "CURRENT_PRODUCT_LOADING";
const CURRENT_PRODUCT_ERROR = "CURRENT_PRODUCT_ERROR";
const CURRENT_PRODUCT_SUCCES = "CURRENT_PRODUCT_SUCCES";

export {
  PRODUCT_LOADING,
  PRODUCT_ERROR,
  PRODUCT_SUCCES,
  CURRENT_PRODUCT_LOADING,
  CURRENT_PRODUCT_ERROR,
  CURRENT_PRODUCT_SUCCES,
};
